<?php

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Info(version: '1.0.0', title: 'Basketball API - Laravel 12', description: 'RESTful API for basketball data management. Supports Bearer Token (Sanctum) or X-Authorization authentication.')]
#[OA\Server(url: 'http://localhost:8000', description: 'Local server')]
#[OA\SecurityScheme(securityScheme: 'sanctum', type: 'http', scheme: 'bearer', bearerFormat: 'Token', description: 'Bearer token via Sanctum (default login)')]
#[OA\SecurityScheme(securityScheme: 'xAuthorization', type: 'apiKey', in: 'header', name: 'X-Authorization', description: 'X-Authorization token for external/legacy systems')]
#[OA\Tag(name: 'Auth')]
#[OA\Tag(name: 'Players')]
#[OA\Tag(name: 'Teams')]
#[OA\Tag(name: 'Games')]

// ── Auth: Register ──────────────────────────────────────────────
#[OA\Post(
    path: '/api/v1/auth/register',
    operationId: 'authRegister',
    tags: ['Auth'],
    summary: 'Register',
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name','email','password','password_confirmation'], properties: [
        new OA\Property(property: 'name', type: 'string', example: 'John Doe'),
        new OA\Property(property: 'email', type: 'string', example: 'john@example.com'),
        new OA\Property(property: 'password', type: 'string', example: 'password123'),
        new OA\Property(property: 'password_confirmation', type: 'string', example: 'password123')
    ])),
    responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Created successfully','data'=>['user'=>['id'=>'01...','name'=>'John Doe','email'=>'john@example.com','role'=>'user'],'token'=>'1|plain_token'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 422, description: 'Validation error', content: new OA\JsonContent(example: ['success'=>false,'message'=>'Invalid data.','errors'=>['email'=>['This email is already in use.']],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))]
)]

// ── Auth: Login (Bearer) ────────────────────────────────────────
#[OA\Post(
    path: '/api/v1/auth/login',
    operationId: 'authLogin',
    tags: ['Auth'],
    summary: 'Login (Bearer Token)',
    description: 'Login for platform users. Returns Sanctum bearer token.',
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['email','password'], properties: [
        new OA\Property(property: 'email', type: 'string', example: 'admin@example.com'),
        new OA\Property(property: 'password', type: 'string', example: 'password')
    ])),
    responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['user'=>['id'=>'01...','email'=>'admin@example.com','role'=>'admin'],'token'=>'1|plain_token'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 401, description: 'Unauthorized', content: new OA\JsonContent(example: ['success'=>false,'message'=>'Invalid credentials.','errors'=>null,'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))]
)]

// ── Auth: X-Login (X-Authorization) ────────────────────────────
#[OA\Post(
    path: '/api/v1/auth/x-login',
    operationId: 'authXLogin',
    tags: ['Auth'],
    summary: 'Login (X-Authorization)',
    description: 'Login for EXTERNAL users only (is_external=true). Returns X-Authorization token.',
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['email','password'], properties: [
        new OA\Property(property: 'email', type: 'string', example: 'external@api.com'),
        new OA\Property(property: 'password', type: 'string', example: 'external123')
    ])),
    responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['user'=>['id'=>'01...','email'=>'external@api.com','role'=>'user'],'x_token'=>'random60chartoken','expires_at'=>'2026-03-06 10:00:00'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 401, description: 'Unauthorized (internal user not allowed)', content: new OA\JsonContent(example: ['success'=>false,'message'=>'Internal users must authenticate via /auth/login.','errors'=>null,'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))]
)]

// ── Auth: Register External ────────────────────────────────────
#[OA\Post(
    path: '/api/v1/auth/register-external',
    operationId: 'authRegisterExternal',
    tags: ['Auth'],
    summary: 'Register External User',
    description: 'Public registration for external API clients. Creates user with is_external=true and returns X-Authorization token.',
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name','email','password','password_confirmation'], properties: [
        new OA\Property(property: 'name', type: 'string', example: 'External Client'),
        new OA\Property(property: 'email', type: 'string', example: 'client@api.com'),
        new OA\Property(property: 'password', type: 'string', example: 'password123'),
        new OA\Property(property: 'password_confirmation', type: 'string', example: 'password123')
    ])),
    responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Created successfully','data'=>['user'=>['id'=>'01...','name'=>'External Client','email'=>'client@api.com','role'=>'user','is_external'=>true],'x_token'=>'random60chartoken','expires_at'=>'2026-03-06 10:00:00'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 422, description: 'Validation error')]
)]

// ── Auth: Logout ────────────────────────────────────────────────
#[OA\Post(path: '/api/v1/auth/logout', operationId: 'authLogout', tags: ['Auth'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Logout', responses: [
    new OA\Response(response: 204, description: 'No content (Bearer)'),
    new OA\Response(response: 200, description: 'Success (X-Authorization)', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Logout successful.','data'=>['revoked'=>true],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))
])]

// ── Auth: Me ────────────────────────────────────────────────────
#[OA\Get(path: '/api/v1/auth/me', operationId: 'authMe', tags: ['Auth'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Current authenticated user', responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['id'=>'01...','name'=>'Administrator','email'=>'admin@example.com','role'=>'admin','is_external'=>false],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))])]

// ── Auth: X-Token Management (Bearer only) ─────────────────────
#[OA\Post(path: '/api/v1/auth/x-token', operationId: 'authCreateXToken', tags: ['Auth'], security: [['sanctum' => []]], summary: 'Create X-Authorization token', description: 'Requires Bearer token. Generates a new X-Authorization token for external integrations.', requestBody: new OA\RequestBody(required: false, content: new OA\JsonContent(properties: [new OA\Property(property: 'name', type: 'string', example: 'integration')])) , responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Created successfully','data'=>['token'=>'plain_x_token','expires_at'=>'2026-03-06 10:00:00'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))])]
#[OA\Delete(path: '/api/v1/auth/x-token', operationId: 'authRevokeXToken', tags: ['Auth'], security: [['sanctum' => []]], summary: 'Revoke X-Authorization token', description: 'Requires Bearer token. Revokes an existing X-Authorization token.', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['token'], properties: [new OA\Property(property: 'token', type: 'string', example: 'plain_x_token')])) , responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['revoked'=>true],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 422, description: 'Validation error')])]

// ── Admin: Toggle User External Status ─────────────────────────
#[OA\Patch(
    path: '/api/v1/admin/users/{user}/toggle-external',
    operationId: 'adminToggleUserExternal',
    tags: ['Auth'],
    security: [['sanctum' => []]],
    summary: 'Toggle user external status (Admin only)',
    description: 'Only administrators can change user external status. Revokes all user tokens when changed.',
    parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, description: 'User ULID', schema: new OA\Schema(type: 'string', example: '01JKEXAMPLE00000000000000'))],
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['is_external'], properties: [
        new OA\Property(property: 'is_external', type: 'boolean', example: true, description: 'true = external (X-Auth), false = internal (Sanctum)')
    ])),
    responses: [
        new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['user'=>['id'=>'01...','email'=>'user@example.com','is_external'=>true],'message'=>'User is now external (use X-Authorization).'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])),
        new OA\Response(response: 403, description: 'Forbidden - Only administrators'),
        new OA\Response(response: 404, description: 'User not found')
    ]
)]

// ── Players ─────────────────────────────────────────────────────
#[OA\Get(path: '/api/v1/players', operationId: 'playersIndex', tags: ['Players'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'List players', description: 'Ability: players:read OR players:*', parameters: [new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', example: 15)), new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string', example: 'LeBron')), new OA\Parameter(name: 'position', in: 'query', schema: new OA\Schema(type: 'string', example: 'F')), new OA\Parameter(name: 'team_id', in: 'query', schema: new OA\Schema(type: 'string', example: '01...')), new OA\Parameter(name: 'is_active', in: 'query', schema: new OA\Schema(type: 'boolean', example: true))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>[['id'=>'01...','first_name'=>'LeBron','last_name'=>'James','position'=>'F','team_id'=>'01...']],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0','pagination'=>['total'=>1,'per_page'=>15,'current_page'=>1,'last_page'=>1]]]))])]
#[OA\Post(path: '/api/v1/players', operationId: 'playersStore', tags: ['Players'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Create player', description: 'Ability: players:create OR players:*', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['first_name','last_name'], properties: [new OA\Property(property: 'first_name', type: 'string', example: 'LeBron'), new OA\Property(property: 'last_name', type: 'string', example: 'James'), new OA\Property(property: 'team_id', type: 'string', nullable: true, example: '01...'), new OA\Property(property: 'position', type: 'string', nullable: true, example: 'F'), new OA\Property(property: 'height', type: 'string', nullable: true, example: '6-9'), new OA\Property(property: 'weight', type: 'string', nullable: true, example: '250'), new OA\Property(property: 'jersey_number', type: 'string', nullable: true, example: '23'), new OA\Property(property: 'college', type: 'string', nullable: true, example: 'St. Vincent-St. Mary HS'), new OA\Property(property: 'country', type: 'string', nullable: true, example: 'USA'), new OA\Property(property: 'draft_year', type: 'integer', nullable: true, example: 2003), new OA\Property(property: 'draft_round', type: 'integer', nullable: true, example: 1), new OA\Property(property: 'draft_number', type: 'integer', nullable: true, example: 1), new OA\Property(property: 'is_active', type: 'boolean', example: true)])) , responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Created successfully','data'=>['id'=>'01...','first_name'=>'LeBron','last_name'=>'James'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 422, description: 'Validation error')])]
#[OA\Get(path: '/api/v1/players/{player}', operationId: 'playersShow', tags: ['Players'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Show player', description: 'Ability: players:read OR players:*', parameters: [new OA\Parameter(name: 'player', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['id'=>'01...','first_name'=>'LeBron','last_name'=>'James','team'=>['id'=>'01...','name'=>'Lakers']],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 404, description: 'Not found')])]
#[OA\Put(path: '/api/v1/players/{player}', operationId: 'playersUpdate', tags: ['Players'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Update player', description: 'Ability: players:update OR players:*', parameters: [new OA\Parameter(name: 'player', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(properties: [new OA\Property(property: 'first_name', type: 'string', example: 'Updated'), new OA\Property(property: 'last_name', type: 'string', example: 'Name'), new OA\Property(property: 'team_id', type: 'string', nullable: true, example: '01...'), new OA\Property(property: 'position', type: 'string', nullable: true, example: 'G'), new OA\Property(property: 'height', type: 'string', nullable: true, example: '6-2'), new OA\Property(property: 'weight', type: 'string', nullable: true, example: '190'), new OA\Property(property: 'jersey_number', type: 'string', nullable: true, example: '30'), new OA\Property(property: 'college', type: 'string', nullable: true, example: 'Duke'), new OA\Property(property: 'country', type: 'string', nullable: true, example: 'USA'), new OA\Property(property: 'draft_year', type: 'integer', nullable: true, example: 2009), new OA\Property(property: 'draft_round', type: 'integer', nullable: true, example: 1), new OA\Property(property: 'draft_number', type: 'integer', nullable: true, example: 7), new OA\Property(property: 'is_active', type: 'boolean', example: true)])) , responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['id'=>'01...','first_name'=>'Updated'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 422, description: 'Validation error')])]
#[OA\Delete(path: '/api/v1/players/{player}', operationId: 'playersDestroy', tags: ['Players'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Delete player', description: 'Ability: players:delete OR players:* (admin only)', parameters: [new OA\Parameter(name: 'player', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Player deleted successfully.','data'=>['id'=>'01...','deleted'=>true],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 403, description: 'Forbidden')])]

// ── Teams ───────────────────────────────────────────────────────
#[OA\Get(path: '/api/v1/teams', operationId: 'teamsIndex', tags: ['Teams'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'List teams', description: 'Ability: teams:read OR teams:*', parameters: [new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', example: 15)), new OA\Parameter(name: 'conference', in: 'query', schema: new OA\Schema(type: 'string', example: 'West')), new OA\Parameter(name: 'division', in: 'query', schema: new OA\Schema(type: 'string', example: 'Pacific')), new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string', example: 'Lakers'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>[['id'=>'01...','name'=>'Lakers','city'=>'Los Angeles']],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0','pagination'=>['total'=>1,'per_page'=>15,'current_page'=>1,'last_page'=>1]]]))])]
#[OA\Post(path: '/api/v1/teams', operationId: 'teamsStore', tags: ['Teams'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Create team', description: 'Ability: teams:create OR teams:*', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name','city','abbreviation','conference','division','full_name'], properties: [new OA\Property(property: 'name', type: 'string', example: 'Lakers'), new OA\Property(property: 'city', type: 'string', example: 'Los Angeles'), new OA\Property(property: 'abbreviation', type: 'string', example: 'LAL'), new OA\Property(property: 'conference', type: 'string', example: 'West'), new OA\Property(property: 'division', type: 'string', example: 'Pacific'), new OA\Property(property: 'full_name', type: 'string', example: 'Los Angeles Lakers')])) , responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Created successfully','data'=>['id'=>'01...','name'=>'Lakers'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 422, description: 'Validation error')])]
#[OA\Get(path: '/api/v1/teams/{team}', operationId: 'teamsShow', tags: ['Teams'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Show team', description: 'Ability: teams:read OR teams:*', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['id'=>'01...','name'=>'Lakers','conference'=>'West'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 404, description: 'Not found')])]
#[OA\Put(path: '/api/v1/teams/{team}', operationId: 'teamsUpdate', tags: ['Teams'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Update team', description: 'Ability: teams:update OR teams:*', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(properties: [new OA\Property(property: 'name', type: 'string', example: 'Updated Team'), new OA\Property(property: 'city', type: 'string', example: 'New City'), new OA\Property(property: 'abbreviation', type: 'string', example: 'UTC'), new OA\Property(property: 'conference', type: 'string', example: 'East'), new OA\Property(property: 'division', type: 'string', example: 'Atlantic'), new OA\Property(property: 'full_name', type: 'string', example: 'New City Updated Team')])) , responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['id'=>'01...','city'=>'New City'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))])]
#[OA\Delete(path: '/api/v1/teams/{team}', operationId: 'teamsDestroy', tags: ['Teams'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Delete team', description: 'Ability: teams:delete OR teams:* (admin only)', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Team deleted successfully.','data'=>['id'=>'01...','deleted'=>true],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/api/v1/teams/{team}/players', operationId: 'teamsPlayers', tags: ['Teams'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'List players by team', description: 'Ability: players:read OR players:*', parameters: [new OA\Parameter(name: 'team', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>[['id'=>'01...','first_name'=>'LeBron','last_name'=>'James']],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))])]

// ── Games ───────────────────────────────────────────────────────
#[OA\Get(path: '/api/v1/games', operationId: 'gamesIndex', tags: ['Games'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'List games', description: 'Ability: games:read OR games:*', parameters: [new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', example: 15)), new OA\Parameter(name: 'season', in: 'query', schema: new OA\Schema(type: 'integer', example: 2023)), new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string', example: 'Final')), new OA\Parameter(name: 'postseason', in: 'query', schema: new OA\Schema(type: 'boolean', example: false))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>[['id'=>'01...','season'=>2023,'status'=>'Final','home_team_score'=>102,'visitor_team_score'=>99]],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0','pagination'=>['total'=>1,'per_page'=>15,'current_page'=>1,'last_page'=>1]]]))])]
#[OA\Post(path: '/api/v1/games', operationId: 'gamesStore', tags: ['Games'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Create game', description: 'Ability: games:create OR games:*', requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['home_team_id','visitor_team_id','season','status','game_date'], properties: [new OA\Property(property: 'home_team_id', type: 'string', example: '01...'), new OA\Property(property: 'visitor_team_id', type: 'string', example: '01...'), new OA\Property(property: 'home_team_score', type: 'integer', example: 100), new OA\Property(property: 'visitor_team_score', type: 'integer', example: 98), new OA\Property(property: 'season', type: 'integer', example: 2023), new OA\Property(property: 'period', type: 'integer', example: 4), new OA\Property(property: 'status', type: 'string', example: 'Final'), new OA\Property(property: 'time', type: 'string', nullable: true, example: '00:00'), new OA\Property(property: 'postseason', type: 'boolean', example: false), new OA\Property(property: 'game_date', type: 'string', example: '2023-10-20')])) , responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Created successfully','data'=>['id'=>'01...','season'=>2023,'status'=>'Final'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 422, description: 'Validation error')])]
#[OA\Get(path: '/api/v1/games/{game}', operationId: 'gamesShow', tags: ['Games'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Show game', description: 'Ability: games:read OR games:*', parameters: [new OA\Parameter(name: 'game', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['id'=>'01...','season'=>2023,'status'=>'Final','home_team'=>['id'=>'01...'],'visitor_team'=>['id'=>'01...']],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 404, description: 'Not found')])]
#[OA\Put(path: '/api/v1/games/{game}', operationId: 'gamesUpdate', tags: ['Games'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Update game', description: 'Ability: games:update OR games:*', parameters: [new OA\Parameter(name: 'game', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(properties: [new OA\Property(property: 'home_team_id', type: 'string', example: '01...'), new OA\Property(property: 'visitor_team_id', type: 'string', example: '01...'), new OA\Property(property: 'home_team_score', type: 'integer', example: 110), new OA\Property(property: 'visitor_team_score', type: 'integer', example: 108), new OA\Property(property: 'season', type: 'integer', example: 2023), new OA\Property(property: 'period', type: 'integer', example: 4), new OA\Property(property: 'status', type: 'string', example: 'Final'), new OA\Property(property: 'time', type: 'string', nullable: true, example: '00:00'), new OA\Property(property: 'postseason', type: 'boolean', example: false), new OA\Property(property: 'game_date', type: 'string', example: '2023-10-21')])) , responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Success','data'=>['id'=>'01...','status'=>'Final'],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']]))])]
#[OA\Delete(path: '/api/v1/games/{game}', operationId: 'gamesDestroy', tags: ['Games'], security: [['sanctum' => []], ['xAuthorization' => []]], summary: 'Delete game', description: 'Ability: games:delete OR games:* (admin only)', parameters: [new OA\Parameter(name: 'game', in: 'path', required: true, schema: new OA\Schema(type: 'string'))], responses: [new OA\Response(response: 200, description: 'Success', content: new OA\JsonContent(example: ['success'=>true,'message'=>'Game deleted successfully.','data'=>['id'=>'01...','deleted'=>true],'meta'=>['timestamp'=>'2026-02-05 10:00:00','version'=>'1.0']])), new OA\Response(response: 403, description: 'Forbidden')])]
class OpenApiSpec
{
}
